language: node_js
node_js:
  - "0.10.33"
services:
  - postgresql
addons:
  postgresql: "9.3"
  sauce_connect: true
sudo: false
notifications:
  email: false
script:
  - npm run syntax
  - npm test
before_script:
  - psql -c 'create database browniepoints_test;' -U postgres
  - cd test/scripts; ./create-db.sh browniepoints_test; cd ../..;
  - PORT=9001 node server/index.js&
  - sleep 5
after_script:
  - npm run coveralls
  - npm run e2e
env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/browniepoints_test
    - AWS_BUCKET=mlf-browniepoints-test
    # AWS_SECRET_ACCESS_KEY
    - secure: VmPrj7W4S6LgtO/iORTLW6TSZBXLeC+KHbZ6d3fHrQ3D9GTwvT18UoZfvTIQzfYdgisMROackf8dAKqVCWGz5YEGKHWUqX2gAFKZKDaOAIyvMpct6IZm+udTKKrq3Bop2IDwn7RCy78bOkEhuSd3IjU0IJ3Jb7V1u1Gas0WOa6M=
    # AWS_ACCESS_KEY_ID
    - secure: PTIMmhboQymaPdqhyN2rLeoRGsNK3LF9qMXiIUCfY1IuU65Ww2EaAOY944q8EVI6qASdj/aLJ78lPEDJloJE/hFTde8+QnsX1CIgnwNMUk4iqJKaG0UIjwILjMkDDi9J81dT/BDzxY8Mcvb8OB8Zf6uS3hUdjVlEEWTPWCeM5MA=
